name: CD - Deploy VPS

on:
  push:
    branches: [ "main", "godav" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Desplegar en VPS por SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_KEY }}
          script: |
            cd Adopciones-CAAM
            git pull origin godav
            docker-compose down
            docker-compose build
            docker-compose up -d
