name: CD - Deploy VPS

on:
  push:
    branches: ["main", "godav"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_KEY }}
          script: |
            set -e

            cd Adopciones-CAAM

            echo "Actualizando repo"
            git fetch origin
            git checkout ${{ github.ref_name }}
            git pull origin ${{ github.ref_name }}

            echo "Limpiando contenedores y cache"
            docker-compose down
            docker system prune -af

            echo "Rebuild completo"
            docker-compose build --no-cache

            echo "Levantando app"
            docker-compose up -d

            echo "Deploy finalizado"
