name: PR - Comentarios automáticos

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  comment:
    runs-on: ubuntu-latest

    steps:
      - name: Comentar el Pull Request
        uses: actions/github-script@v7
        with:
          script: |
            const actor = context.actor;
            const branchFrom = context.payload.pull_request.head.ref;
            const branchTo = context.payload.pull_request.base.ref;

            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: `Hola @${actor}!\n\n Parece que cambiaron algo.\n\n Rama origen: **${branchFrom}**\n Rama destino: **${branchTo}**\n\n Se ejecutarán automáticamente:\n- Tests unitarios\n- Build de Next.js\n- Validaciones de CI\n\n Y hasta un mensaje de navidad, ya acabate semestre. Por favor espera a que GitHub Actions acabe todo mi sufrimiento.`
            });
